### ISSUE TITLE
mixed types for numbers

### ISSUE THREAD

**Issue by valevo** [colonial-heritage/research-guides-dev#1]
issue
----

here the year is given as an integer type: https://github.com/colonial-heritage/research-guides-dev/blob/ad7389401dd5eee65d5c9a3b9500aec987f7abee/niveau3/version2/NZG_v02_20240314.yml#L23 

but here it is given as a string type: https://github.com/colonial-heritage/research-guides-dev/blob/ad7389401dd5eee65d5c9a3b9500aec987f7abee/niveau3/version2/KKZ_v02_20240313.yml#L28 

#### explanation

the difference is the quotation marks (") around the year. quotation marks are _optional_ for string types (i.e. anything textual) but the presence of quotation marks _always_ indicates a string type. so `"hello"`  and `hello` have the same type (namely string) but `1964` and `"1964"` do *NOT* have the same type (the first is of type integer and the second of type string)

instructions
---

please be consistent in the types you use for instance of the same data. specifically, for dates **that consist only of years** it isn't _that_ important if you use integer type or string type, as long as it's consistent.

note: a **full** date in the representation `1986-02-23` **cannot** be an integer and will always be a string (like the word `hello`), because it *isn't* a number_ (the character `-` cannot appear in numbers)

**Comment by wreints** [comment]
I updated the years so that all of them are in quotation marks. As far as I could see, this was only needed in the NZG one.
