### ISSUE TITLE
'abstracts' for research guides?

### ISSUE THREAD

**Issue by valevo** [colonial-heritage/research-guides-dev#10]
## background

 - cards on RG landing page could use small extra descriptions (other than the RG title)
 - tooltips for links to RGs from elsewhere in the Datahub would be useful (e.g. on hovering)

## TODO

 - add abstracts to RGs of level 2 and 3 -- one to two sentences, no more than 150-200 characters

**Comment by valevo** [comment]
agreed to be a useful extension and decided to implement

**Comment by wreints** [comment]
Done!

**Comment by wreints** [comment]
Abstracts were decided to be too descriptive. I'll make 'm more informative.

**Comment by wreints** [comment]
Done for all the RGs
