### ISSUE TITLE
make main texts of guides just one field in YAML

### ISSUE THREAD

**Issue by valevo** [colonial-heritage/research-guides-dev#14]
## background

 - RGs consist (among other types of information) of main texts, that are currently stored in the YAML files as the values of keys (that are the titles, or section headers, of those texts) on the top level of the file
 - (to some extent _because_ we're taking shortcuts for now) it's easier from a linked data modelling perspective, to have only one main text field for each YAML file

## decision

 - put all _main_ texts of an RG inside of a single key and use Markdown to separate the section from each other and keeping their headings/names (this key could be named anything, e.g. `main-text`)
 - choosing the right Markdown processors in the front-end will still allow adaptable formatting of sections & collapsible sections
 - 

## TODO

Something like 
```
Description:
   content: |
       some description **text**.
   content-type: "text/markdown"

Provenance research:
   content: |
       info about doing _provenance_ research.
   content-type: "text/markdown"
```

becomes 
```
main-text:
  content: | 
    ## Description
    
    some description **text**.
    
   
    ## Provenance research
    
    info about doing _provenance_ research.
  
  content-type: "text/markdown"
```

Since section headers are now no longer variable names in the YAML but inside of text, they should be translated into Dutch/English (besides formatting, contents of texts are not altered in the front-end).

**Comment by wreints** [comment]
Would this be the way? 

<details>
<summary>Description</summary>
[Content]
</details>
<details>
<summary>Provenance research</summary>
[Content]
</details>

Doing it this way would also mean that I need  to change the language of Description and Provenance research into Dutch (for the Dutch RAs), right?

**Comment by valevo** [comment]
see above; what you posted is nice but is technically HTML and not Markdown (and although most Markdown processors accept HTML code, we want to keep it pure Markdown, so as to not mix text annotation and text formatting). A good Markdown processor will turn the Markdown I wrote above automatically into HTML similar to what you wrote.

**Comment by wreints** [comment]
@valevo Looks good, I'll add it to the RAs. How should I approach this for the Level 1s?
