### ISSUE TITLE
human-readable vs concept links for Wikidata

### ISSUE THREAD

**Issue by valevo** [colonial-heritage/research-guides-dev#15]
## TODO

 - replace Wikidata links to human-readable pages with concept URIs, so e.g. https://www.wikidata.org/wiki/Q34076860 becomes http://www.wikidata.org/entity/Q34076860

## advantages 

 - concept URIs are machine-readable, make it possible to automatically pull information from Wikidata into RGs/Datahub
 - concept URIs automatically resolve to human-readable Wiki links in browser contexts, so for front-end applications it doesn't make a difference

**Comment by wreints** [comment]
Should be applied to all URIs now. I also did this for AAT URIs and GeoNames
