### ISSUE TITLE
"Identifiers" don't need location indicated

### ISSUE THREAD

**Issue by valevo** [colonial-heritage/research-guides-dev#2]
issue
----

in this example, the identifier `"Wikidata: https://www.wikidata.org/wiki/Q34076860"` includes the location (Wikidata) of the identifier:
https://github.com/colonial-heritage/research-guides-dev/blob/ad7389401dd5eee65d5c9a3b9500aec987f7abee/niveau3/version2/KKZ_v02_20240313.yml#L5

this is not necessary (we can infer it from the domain prefix "https://www.wikidata.org" in the link) and actually makes parsing more complex for us

instructions
---

please only give the link, in this case `"https://www.wikidata.org/wiki/Q34076860"`

#### note

in this example, the **entire** list item `"Wikidata: https://www.wikidata.org/wiki/Q34076860"` is a single element of type string; if you intended the list item to be a key-value pair, the data entry would have to be `"Wikidata": "https://www.wikidata.org/wiki/Q34076860"` (notice the placement of the quotation marks); but, again, this is superfluous because we know the domain of the resource from the link itself

**Comment by wreints** [comment]
Fixed this as well, all the identifiers should now only consist of a link, without a "name:" part.
