### ISSUE TITLE
in niveau2, file names are still different between English and Dutch

### ISSUE THREAD

**Issue by valevo** [colonial-heritage/research-guides-dev#24]
please fix asap

**Comment by wreints** [comment]
This also applies to the RAs on the other levels, right? So, for once and for all: the file names of both the Dutch and English RAs should be the same and they can only be distinguished by looking in what folder they are?

**Comment by valevo** [comment]
exactly

**Comment by wreints** [comment]
OK, then I'll change this for all the RAs
