### ISSUE TITLE
"identifiers" in "Relevant data" is not a list

### ISSUE THREAD

**Issue by valevo** [colonial-heritage/research-guides-dev#30]
e.g. here: https://github.com/colonial-heritage/research-guides-dev/blob/43d08d3785bdbdf401a79c3459735e09343652da/niveau3/English/PieterPott_20240508.yml#L16

 "identifiers" in "Relevant data" is not a list but a simple string --> identifiers always needs to be a list, even when only consisting of one item

so 
```
"Relevant data":
    "identifiers": "https://www.wikidata.org/..."
```
 should become
```
"Relevant data":
    "identifiers": 
         - "https://www.wikidata.org/..."
```

**Comment by wreints** [comment]
Should be correct in all the RAs now!
