### ISSUE TITLE
type is list, needs to be dict

### ISSUE THREAD

**Issue by valevo** [colonial-heritage/research-guides-dev#31]
seems like this issue is in all level 3 RGs (and possibly in level 2 as well) but e.g. in 
https://github.com/colonial-heritage/research-guides-dev/blob/43d08d3785bdbdf401a79c3459735e09343652da/niveau3/Dutch/NZG_20240314.yml#L43

in field "Main-text" contains a list, not a dictionary (with keys "content" and "content-type")

so
```
"Main-text":
   - content: |
            some text
  - content-type: "ext/markdown"
```

needs to be

```
"Main-text":
     content: |
            some text
     content-type: "ext/markdown"
```

**Comment by valevo** [comment]
please fix asap, blocks front-end work

**Comment by wreints** [comment]
Done for level 2 now. But for the future (next week), if there are such small changes that are very important for the front-end, which do not change anything to the content of the RA, please make the needed changes yourself if you see them. Same goes for typos or other listing problems. I'll try to fix the Level3's asap

**Comment by valevo** [comment]
thanks for suggesting that but we have a fairly strict policy (for good reasons) to not mess with source data

**Comment by wreints** [comment]
OK, that makes sense. Done for Level 3 now as well.
