### ISSUE TITLE
Invalid IRI

### ISSUE THREAD

**Issue by Sabachi** [colonial-heritage/research-guides-dev#35]
1. At level 2 for both languages ( Dutch, English ) the file `CivilServants` contains invalid IRI. 

In both files, the value of the field [Link](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau2/Dutch/CivilServants_Dutch.json#L71) is string, but an IRI is expected here. For example, see the value of the field [Link](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau2/Dutch/ChristianMission_Dutch.json#L64) in the file `ChristianMission_Dutch`.

2. The file `KKZ_Dutch` contains invalid IRI, which is the value of the field [Link](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/Dutch/KKZ_Dutch.json#L173)

**Comment by wreints** [comment]
Solved!
