### ISSUE TITLE
`Soort _bron` instead of `Type of source`

### ISSUE THREAD

**Issue by Sabachi** [colonial-heritage/research-guides-dev#36]
1. In the file `KVVAK_Dutch` the key `Type of source` is written as `Soort _bron` [here](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/Dutch/KVVAK_Dutch.json#L104)

2. In the file `KKZ_English` the key `Type of source` is written as `Soort _bron`[here](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/KKZ_English.json#L126)

**Comment by wreints** [comment]
Solved!
