### ISSUE TITLE
Variation in source data format

### ISSUE THREAD

**Issue by Sabachi** [colonial-heritage/research-guides-dev#37]
[Tags](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/NZG_English.json#L24) in the file `NZG_English` is an object that contains two strings and 1 list. But if this is compared to [Tags](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/KunsthandelVanLier_English.json#L40) in the file `KunsthandelVanLier_English`, then one would observe that the object `Tags` contains 3 lists. 

It is important for the ETL, that the source data is supplied in the same data format.

**Comment by wreints** [comment]
Should be solved!
