### ISSUE TITLE
Missing 'Primary sources' in Science_English.json

### ISSUE THREAD

**Issue by ivaDimitrova07** [colonial-heritage/research-guides-dev#38]
One of the new JSON files is [`Science_English`](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau2/English/Science_English.json) for Level 2 in English.
 In this file the field for Primary sources [seems to be empty](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau2/English/Science_English.json#L114). Is this intended? Do we want to accommodate such cases?

Currently, this irregularity causes the ETL to fail which prevents updating the Knowledge Graph.

Let me know what you think so we know how to adjust the ETL script if needed.

**Comment by wreints** [comment]
Thanks for pointing this out, I've let the Primary Sources blank intentionally since there were no Primary sources to add. If this causes the ETL to fail, is it better to fully erase the Primary Sources paragraph?

**Comment by ivaDimitrova07** [comment]
Yes, that should be good enough to solve the issue! 
note: this is the case for the Dutch version as well.

**Comment by wreints** [comment]
OK, done!
