### ISSUE TITLE
Irregular strcuture in CivilServants_English.json

### ISSUE THREAD

**Issue by ivaDimitrova07** [colonial-heritage/research-guides-dev#39]
In CivilServants_English, one of the names for secondary sources seems to have a different (looking incorrect as well) structure - see [here](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau2/English/CivilServants_English.json#L125). 
Is this intended?

This causes the ETL to fail and is a blocker for us.

Let me know what you think.

**Comment by wreints** [comment]
That was a mistake from my side, solved it now!
