### ISSUE TITLE
naming patterns

### ISSUE THREAD

**Issue by valevo** [colonial-heritage/research-guides-dev#4]
## background

 - _disclaimer_: these comments are overly nit-picky but make our lives for processing and parsing by automated processes a pain 
 - the folder [version 2](https://github.com/colonial-heritage/research-guides-dev/tree/main/niveau2/version%202) of "niveau2" contains a space (between "version" and "2") but other folders in the same naming pattern (e.g. "version1" in "niveau2" or "version2" in "niveau3")
 - the [Dutch version folder](https://github.com/colonial-heritage/research-guides-dev/tree/main/niveau1/Nederlands) in "niveau1" is called "Nederlands" while its English complement is called "English"; the Dutch versions in "niveau2" and "niveau3" are called "Dutch"
 - in "niveau1", the English version have names that are translations of the Dutch versions (e.g. [DoingResearch_v01_20240425.yml](https://github.com/colonial-heritage/research-guides-dev/blob/main/niveau1/English/DoingResearch_v01_20240425.yml)); in "niveau2", English versions have the Dutch name and the English translation in braces, together with an "ENG" language tag (e.g. https://github.com/colonial-heritage/research-guides-dev/blob/main/niveau2/version%202/English/Handel(Trade)_ENG_20240316.yml])

## TODO

 - important: please generally avoid white spaces in file and folder names (as in "version 2") because they make processing more complicated (yes, it's silly, but that's just how it is); you can always use characters allowed in URLs, the set of these characters is listed [here](https://en.wikipedia.org/wiki/Percent-encoding#Types_of_URI_characters) 
 - please ensure uniform naming patterns _that are exact_
 - please make choices regarding language of file and folder names and stick to them; the choice is your but please try to make it consistent
 - repeated information (such as "ENG" in filenames in the folder called "English") doesn't help processing and can be avoided

**Comment by wreints** [comment]
- I changed the "version 2" folder of "niveau2" to "version2".
- Renamed all the folders with the RG's in Dutch to "Dutch"
- And changed the names of the files (removed the versions from the name, since they are in the folder corresponding the version). The question rises whether we need to create something to link the Dutch and English versions to each other, since it might not always be clear which RG's are which.
