### ISSUE TITLE
Link field for Primary sources has a different strcuture

### ISSUE THREAD

**Issue by ivaDimitrova07** [colonial-heritage/research-guides-dev#40]
In one of the Level 3 files - KKZ_English.json, the field for Link in the Primary sources the structures does not follow the regular pattern.
The link [in this case](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/KKZ_English.json#L92) is stored as a value of "Link", [rather than being stored in "URL" within "Link"](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/KKZ_English.json#L133). 
Following the same structure would ensure that the ETL script is producing the expected knowledge graph.
Let me know what you think.

**Comment by wreints** [comment]
You're right, I've changed it to the right structure!
