### ISSUE TITLE
Markdown in niveau3/Dutch/PieterPott_20240312.yml

### ISSUE THREAD

**Issue by CamideK55** [colonial-heritage/research-guides-dev#41]
Check markdown in niveau3/Dutch/PieterPott_20240312.yml [this line](https://github.com/colonial-heritage/research-guides-dev/blob/d0530b330010b4be017ac9dc848df0d2fcd2d402/niveau3/Dutch/PieterPott_20240312.yml#L48). 
->
`[Prajnaparamita-beelden](https://hdl.handle.net/20.500.11840/916233; https://hdl.handle.net/20.500.11840/916234; https://hdl.handle.net/20.500.11840/916235; https://hdl.handle.net/20.500.11840/916236)`

This markdown is shown as e.g.
![image](https://github.com/user-attachments/assets/dbbed3b1-7364-4302-9abf-31df942b308a)

**Comment by wreints** [comment]
Solved (both in NL and ENG version)!
