### ISSUE TITLE
Markdown in English/PieterPott_20240508.yml

### ISSUE THREAD

**Issue by CamideK55** [colonial-heritage/research-guides-dev#42]
Check markdown in niveau3/English/PieterPott_20240508.yml on[ this line.](https://github.com/colonial-heritage/research-guides-dev/blob/d0530b330010b4be017ac9dc848df0d2fcd2d402/niveau3/English/PieterPott_20240508.yml#L48)
->
`[Prajnaparamita statues](https://hdl.handle.net/20.500.11840/916233; https://hdl.handle.net/20.500.11840/916234; https://hdl.handle.net/20.500.11840/916235; https://hdl.handle.net/20.500.11840/916236)`

This markdown is shown as e.g.
![image](https://github.com/user-attachments/assets/a4f69d3f-8826-4026-b0f3-ea62792ea2c5)

**Comment by wreints** [comment]
Solved
