### ISSUE TITLE
Link field for Primary sources has a different strcuture - level 2

### ISSUE THREAD

**Issue by ivaDimitrova07** [colonial-heritage/research-guides-dev#43]
Similar to issue #40 , same can be noticed in the CivliServant_Dutch.json file - see line [94](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau2/Dutch/CivilServants_Dutch.json#L94).

**Comment by wreints** [comment]
Solved

**Comment by ivaDimitrova07** [comment]
similar also here in NZG_Dutch [line 97](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/Dutch/NZG_Dutch.json#L97)
