### ISSUE TITLE
`TopLevel_English` file has missing fields and fields written in Dutch

### ISSUE THREAD

**Issue by Sabachi** [colonial-heritage/research-guides-dev#44]
1. Field written in Dutch : [Deelonderwerpen](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau0/English/TopLevel_English.json#L158) is written in Dutch but instead should be `Subtopics`. For example, check this [link](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau0/English/TopLevel_English.json#L142C22-L142C31).

2. Missing field : Field `linkFilename` is missing in [this list](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau0/English/TopLevel_English.json#L158).

**Comment by wreints** [comment]
@Sabachi 

1. I changed the 'deelonderwerpen' in 'subtopics'
2. I don't provide the field `linkFilename` in the yaml, so i don't know how that shows in the json and what the reason is why it doesn't show in the specific list.. Maybe it has to do something with Valentin's script?

**Comment by wreints** [comment]
@Sabachi Is this solved?

**Comment by ivaDimitrova07** [comment]
the issue seems resolved, thanks
