### ISSUE TITLE
Typo in KKZ_English

### ISSUE THREAD

**Issue by ivaDimitrova07** [colonial-heritage/research-guides-dev#45]
There is a typo about "Type of source" on [line 110](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/KKZ_English.json#L110). The typo is not present for the [Dutch version](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/Dutch/KKZ_Dutch.json#L117) of this file

**Comment by wreints** [comment]
Solved!
