### ISSUE TITLE
Some fields are not fully translated in KKZ_English

### ISSUE THREAD

**Issue by ivaDimitrova07** [colonial-heritage/research-guides-dev#46]
On some lines (just a couple) the fields still have their Dutch name. See[ line 132](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/KKZ_English.json#L132), further down also [136,](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/KKZ_English.json#L136) and [142](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/KKZ_English.json#L142).
This causes the ETL to fail but for the moment I can change that manually in the assets on our side.

**Comment by wreints** [comment]
Solved!
