### ISSUE TITLE
Duplicates or non-translated values for name variantons in some of level 3 files

### ISSUE THREAD

**Issue by ivaDimitrova07** [colonial-heritage/research-guides-dev#47]
It looks like the values for names are not translated, which causes duplicates in the Knowledge Graph. For example, here you can see the name variations in the Dutch version of [file KVAAK](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/Dutch/KVVAK_Dutch.json#L18) and here are the name variations in the [English file](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/KVVAK_English.json#L18). They are identical, but because the ETLs work in such way that a language tag is assigned, the triples are not exactly identical. See the structured data in the Knowledge Graph [here](https://data.colonialcollections.nl/NIOD-researchGuide/NIOD-researchGuide/browser?resource=https%3A%2F%2Fdata.colonialcollections.nl%2Fniveau3%2Fid%2FresearchGuide%2FKVVAK).

**Comment by wreints** [comment]
How should we solve this?

**Comment by wreints** [comment]
Okay, but it would be good for Research Aides that don't have an translated name to also show the dutch name variations.

**Comment by wreints** [comment]
@ivaDimitrova07 Is this solved?

**Comment by ivaDimitrova07** [comment]
i still see [duplicates](https://data.colonialcollections.nl/NIOD-researchGuide/NIOD-researchGuide/browser?resource=https%3A%2F%2Fdata.colonialcollections.nl%2Fniveau3%2Fid%2FresearchGuide%2FKVVAK), but i am also not sure if this is a big issue in general
