### ISSUE TITLE
Valid dates

### ISSUE THREAD

**Issue by Sabachi** [colonial-heritage/research-guides-dev#48]
In some cases the dates are present as a localized literal value, for example check this [link](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/Naturalis_English.json#L97).

Is it possible to add a valid date value instead of a string like "Now", "Heden", "Still active".

**Comment by wreints** [comment]
Well, these institutions (or other entities) are still active, so what date should I give it? I can also leave it empty when it doesn't have an 'end' date?

**Comment by wreints** [comment]
@Sabachi Could you please clarify this issue?
