### ISSUE TITLE
Use both English and Dutch translations consistently

### ISSUE THREAD

**Issue by Sabachi** [colonial-heritage/research-guides-dev#49]
In some cases, for example the [Naturalis English file](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/Naturalis_English.json#L132) for type source the value of the fields `Name` and `Descriptions and remarks' is in Dutch language. But in the Naturalis ( Dutch language) file the field Magazine is not present. 

It is possible to keep the English language translation in the English json file and the Dutch language translation in the Dutch json file? And, also is it possible to have both the translations?

**Comment by wreints** [comment]
Hmm, I do'nt know whether I understand your question correctly. When possible I have translated the values of the fields to English (the type of source, for instance). But for some values (names of institutions, names of books or articles), it does not make sense to translate the value of the field. Does that answer your question?

**Comment by wreints** [comment]
@Sabachi Could you please clarify this issue

**Comment by ivaDimitrova07** [comment]
i think your answer explains it, especially the part where you say that the names are purposely not translated. also, i see that "Descriptions and remarks" field is now translated and present for both the [english](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/Naturalis_English.json#L150) and [dutch](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/Dutch/Naturalis_Dutch.json#L134) files for naturalis.
