### ISSUE TITLE
URIs of geographical tags

### ISSUE THREAD

**Issue by Sabachi** [colonial-heritage/research-guides-dev#50]
Please see the geographical tags in this [link](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/Naturalis_English.json#L90). one geographical tag points to "https://www.geonames.org/6255149", another points to "https://geonames.org/6255151" (without "www"). Is it possible to use the same URL format?

For the front end @sdevalk would prefer URIs that point to linked data resources, e.g. "https://sws.geonames.org/6255149/".
If for some reason you disagree with the approach proposed by Sjors, could you please reach out to him ?

**Comment by wreints** [comment]
Sure, I'll have a look at that. Fine to provide the URIs that point to linked data resources, I was not aware I wasn't doing that already.
