### ISSUE TITLE
Link field has a different strcuture

### ISSUE THREAD

**Issue by ivaDimitrova07** [colonial-heritage/research-guides-dev#51]
Similar to issues [#40](https://github.com/colonial-heritage/research-guides-dev/issues/40) and [#43](https://github.com/colonial-heritage/research-guides-dev/issues/43), the newly added 2 files to Level 3 - [Bronbeek](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/Dutch/Bronbeek_Dutch.json) and [MissiemuseumSteyl](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/Dutch/MissiemuseumSteyl_Dutch.json#L76) have different than the agreed structure for Links in the sources fields.

**Comment by ivaDimitrova07** [comment]
same for [RijksmuseumAmsterdam_Dutch](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/Dutch/RijksmuseumAmsterdam_Dutch.json#L120) (although the field is empty)

**Comment by wreints** [comment]
Should be solved
