### ISSUE TITLE
Name variantions fields are not completely empty

### ISSUE THREAD

**Issue by ivaDimitrova07** [colonial-heritage/research-guides-dev#52]
If the field for Name variations is empty, such as the case for file [MissiemuseumSteyl](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/Dutch/MissiemuseumSteyl_Dutch.json#L32), could you please leave it fully empty, rather than adding []?

**Comment by ivaDimitrova07** [comment]
similar situation with [Link](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/Dutch/RMO_Dutch.json#L113) here - the quotation marks are not necessary. could you please remove them?
ideally for both fields, if they are empty, the data would look like:
  "Name variations": [],
and
  "Link": [],

**Comment by ivaDimitrova07** [comment]
yess.
so currently in the [Missiemuseum Steyl](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/Dutch/MissiemuseumSteyl_Dutch.json#L32), the format of "Name variations" is:
"Name variations": [
            []
        ].

what would be the most convenient for us would be if it looked like this:

"Name variations": [ ].

in this way, our script still recognizes that "Name variations" is an array, but it's just empty.

if a link is empty, for the fields of  "Sources", then please follow the structure of:
"Link" : **[ ]**,
 rather than
 "Link" : *anything else without square brackets*. 
the reason is similar to the situation with "Name variations" - the field should be of type array (empty or not).

about the quotation marks - it seems like they are present in the [json files](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/Dutch/RMO_Dutch.json#L60), maybe it's automatic?

**Comment by ivaDimitrova07** [comment]
same for [Primary sources and Secondary sources](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/RijksmuseumAmsterdam_English.json#L116) : 
"Primary sources": null,
 "Secondary sources": null
instead would be:
"Primary sources": [],
 "Secondary sources": []

and ["Name variantions" : "[]"](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/RijksmuseumAmsterdam_English.json#L81)
instead would be
"Name variantions" : []

**Comment by ivaDimitrova07** [comment]
thanks! also for the dutch file about Bronbeek we have the same thing we[ "Name variations" : "[]"](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/Dutch/Bronbeek_Dutch.json#L25) and [Within the hub](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/Dutch/Bronbeek_Dutch.json#L49)

**Comment by wreints** [comment]
Should be solved!

**Comment by ivaDimitrova07** [comment]
yes, all reported inconsistencies in this issue have been solved! thanks
