### ISSUE TITLE
Link structure 

### ISSUE THREAD

**Issue by ivaDimitrova07** [colonial-heritage/research-guides-dev#54]
in KVVAK_English, one of the "Link" fields contains a non-array value - see line [124](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/KVVAK_English.json#L124). instead, it should be:

```
 "Link": [
                {
                    "URL": "https://hdl.handle.net/21.12102/F3CA33316B0B49EEB6E8C0BC9BCAFDD4"
                }
            ],
```

**Comment by wreints** [comment]
Solved
