### ISSUE TITLE
Different name for the files

### ISSUE THREAD

**Issue by Sabachi** [colonial-heritage/research-guides-dev#55]
In the email of 19th December, Maarten raised the following concern:

> At the moment, it appears the tree defined in the top-level research guide is ignored and that instead a tree is generated from the “related items” defined in the second-level research guides.
> As an example: the website currently displays under the heading “Handel” the following (third-level) research guides:
> 
> - Etnografisch Museum Artis
> - Kunsthandel Van Lier
> - Wereldmuseum Amsterdam
> - Wereldmuseum Leiden
> - Wereldmuseum Rotterdam
> 
>  However, the top-level research guide also specifies that the following research guides should fall under the heading “Handel”:
> 
> - Groote Koninklijke Bazar
> - Koninklijke Vereniging Vrienden der Aziatische Kunst
> - Koninklijk Kabinet van Zeldzaamheden 

Please note the following points about the research guides which are missing and not currently present under the heading `Handel`.
For all these points, the file name present in the [Top level English research guide](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau0/English/TopLevel_English.json) is different than the file name present in the individual files ( please look for the field `File name`). 

1. Groote Koninklijke Bazar
In the `Top level English research guide` the value for the field `linkFilename` is [niveau3/English/KoninklijkeBazaar_English](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau0/English/TopLevel_English.json#L57). Please note that the ETL extracts the file name from the value of the field `linkFilename`. In the file [KoninklijkeBazar_English](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/KoninklijkeBazar_English.json) the file name is [KoninklijkeBazar](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/KoninklijkeBazar_English.json#L164C19-L164C35). The two file names are different. They need to be the same, otherwise for the ETL the file name `KoninklijkeBazaar` is different than the file name `KoninklijkeBazar`.  

2. Koninklijke Vereniging Vrienden der Aziatische Kunst
In the `Top level English research guide` the value for the field `linkFilename` is [niveau3/English/RAAS_English](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau0/English/TopLevel_English.json#L71) but in the file [KVVAK_English](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/KVVAK_English.json) the value of the field `File name` is [KVVAK](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/KVVAK_English.json#L195C6-L195C15). For the ETL, `RAAS` and `KVVAK` are two different names. 

3. Koninklijk Kabinet van Zeldzaamheden
In the `Top level English research guide` the value for the field `linkFilename` is [niveau3/English/RCC_English](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau0/English/TopLevel_English.json#L85C33-L85C78) but in the file [KKZ_English](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/KKZ_English.json) the value of the field `File name` is [KKZ](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/KKZ_English.json#L239). For the ETL, `RCC` and `KKZ` are two different names. 

Suggestion:

1. In the top level guides ( irrespective of the language) please write the same file name which is present in the file. 
2. In the top level guides,  file name is the value for the field `linkFilename`, [link to an example](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau0/English/TopLevel_English.json#L85C34-L85C46).
3. In the file, file name is the value for the field  `File name`, [link to an example](https://github.com/colonial-heritage/research-guides-dev/blob/main/forKinsukAndSjors/niveau3/English/KKZ_English.json#L239).

**Comment by Maarten86** [comment]
Hi Kinshuk,

I changed all instances of bazaarto bazar, rcc to kkz, and raas to kvvak. I think the bug was on the English top level research guide only. I hope this worked, at the moment the website only shows the Bazar research guide instead of the top level research guide. I'm still available tomorrow and can act quickly if needed. Keep me posted here if something is/goes wrong!

All the best,
Maarten

**Comment by Sabachi** [comment]
Hi Maarten, 

Thank you !! Yes, the change worked, I have just triggered the pipeline. Tomorrow morning I will check the front end. 
But I have a question : Could you please explain with some screen shot or example what you mean by the following sentence:

> at the moment the website only shows the Bazar research guide instead of the top level research guide

**Comment by Sabachi** [comment]
Hi Maarten, 
Do you mean this view:
![image (2)](https://github.com/user-attachments/assets/1ccf4102-ab61-49c6-973c-e6f9e057310a)

I have informed @sdevalk and @barbarah about this, will keep you posted.

**Comment by Maarten86** [comment]
Yes, indeed, that’s what I see as well. It seems to display some content from a random research guide now on the research guide homepage. It was the Royal Bazar earlier, but now it is Missiemuseum Steyl for me too indeed.

**Comment by Sabachi** [comment]
Hi @Maarten86 , 
The front end is back https://app.colonialcollections.nl/nl/research-guide
If you agree with all the changes, this ticket can be closed.

**Comment by Maarten86** [comment]
I can confirm, thanks for solving this!
