### ISSUE TITLE
link names & digital accessibility

### ISSUE THREAD

**Issue by valevo** [colonial-heritage/research-guides-dev#9]
## background

 - digital accessibility tools such as screen readers read all the link _labels_ on a given website)

## TODO

 - best practice: make link labels in markdown text meaningful (e.g. avoid something like `click [here](http://www.example.com) for more information` and write something like `[Example](http://www.example.com) has more information`

**Comment by wreints** [comment]
This should be fixed on all the current RGs as well. Let me know if you find some mistakes!
